const questions = [
  {
    id: 1,
    question: "The company increased its (　), improving short-term liquidity.",
    translation: "会社は現金及び预金を増やし、短期的な流動性を改善した。",
    choices: ["Cash and deposits", "Short-term loans receivable", "Securities"],
    meanings: ["現金及び預金", "短期貸付金", "有価証券"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産'
  },
  {
    id: 2,
    question: "The company purchased (　) as a short-term investment.",
    translation: "会社は短期投資として有価証券を購入した。",
    choices: ["Securities", "Merchandise", "Accounts receivable - trade"],
    meanings: ["有価証券", "商品", "売掛金"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産'
  },
  {
    id: 3,
    question: "The company holds (　) as negotiable instruments awaiting payment.",
    translation: "会社は支払期日を待つ受取手形を保有している。",
    choices: ["Notes receivable - trade", "Accounts receivable - trade", "Accrued revenue"],
    meanings: ["受取手形", "売掛金", "未収収益"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産'
  },
  {
    id: 4,
    question: "Sales on credit are recorded as (　) until cash is received.",
    translation: "掛け売上は現金が回収されるまで売掛金として計上される。",
    choices: ["Accounts receivable - trade", "Advances received", "Securities"],
    meanings: ["売掛金", "前受金", "有価証券"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産'
  },
  {
    id: 5,
    question: "Interest earned but not yet received is recognized as (　).",
    translation: "未受取の利息は未収収益として認識される。",
    choices: ["Accrued revenue", "Interest income", "Accounts receivable - other"],
    meanings: ["未収収益", "受取利息", "未収入金"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産'
  },
  {
    id: 6,
    question: "Materials held for production are reported as (　).",
    translation: "生産に使用するために保有している原材料として計上される。",
    choices: ["Raw materials", "Finished goods", "Work in process"],
    meanings: ["原材料", "製品", "仕掛品"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産'
  },
  {
    id: 7,
    question: "Buildings used in operations are classified as (　).",
    translation: "営業に使用される建物は有形固定資産に分類される。",
    choices: ["Property, plant and equipment", "Intangible assets", "Current assets"],
    meanings: ["有形固定資産", "無形固定資産", "流動資産"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産'
  },
  {
    id: 8,
    question: "Patent rights owned by the company are recorded as (　).",
    translation: "会社が所有する特許権は無形固定資産として記録される。",
    choices: ["Intangible assets", "Property, plant and equipment", "Current assets"],
    meanings: ["無形固定資産", "有形固定資産", "流動資産"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産'
  },
  {
    id: 9,
    question: "Excess earning power from a business acquisition is recorded as (　).",
    translation: "事業買収による超過収益力はのれんとして計上される。",
    choices: ["Goodwill", "Intangible assets", "Investment securities"],
    meanings: ["のれん", "無形固定資産", "投資有価証券"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産'
  },
  {
    id: 10,
    question: "Programs developed for internal use are classified as (　).",
    translation: "内部使用目的で開発されたソフトウェアとして分類される。",
    choices: ["Software", "Patent right", "Supplies"],
    meanings: ["ソフトウエア", "特許権", "貯蔵品"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産'
  },
  {
    id: 11,
    question: "Goods purchased on credit from suppliers are recorded as (　).",
    translation: "仕入先から掛けで購入した代金は買掛金として計上される。",
    choices: ["Accounts payable - trade", "Notes payable - trade", "Accrued expenses"],
    meanings: ["買掛金", "支払手形", "未払費用"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '負債'
  },
  {
    id: 12,
    question: "Salaries earned by employees but not yet paid are recorded as (　).",
    translation: "従業員が既に勤務して発生しているがまだ支払われていない給与は未払費用として計上される。",
    choices: ["Accrued expenses", "Accounts payable - other", "Advances received"],
    meanings: ["未払費用", "未払金", "前受金"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '負債'
  },
  {
    id: 13,
    question: "Income received in advance from customers is recorded as (　).",
    translation: "顧客から前払いされた収入は前受金として記録される。",
    choices: ["Advances received", "Deposits received", "Accrued expenses"],
    meanings: ["前受金", "預り金", "未払費用"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '負債'
  },
  {
    id: 14,
    question: "Bonds issued by the company are recorded as (　).",
    translation: "会社が発行した債券は社債として記録される。",
    choices: ["Bonds payable", "Long-term borrowings", "Short-term borrowings"],
    meanings: ["社債", "長期借入金", "短期借入金"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '負債'
  },
  {
    id: 15,
    question: "Completed products ready for sale are classified as (　).",
    translation: "販売可能な完成品は製品として分類される。",
    choices: ["Finished goods", "Work in process", "Raw materials"],
    meanings: ["製品", "仕掛品", "原材料"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産'
  },
  {
    id: 16,
    question: "The company recorded (　) for anticipated customer defaults.",
    translation: "会社は見込まれる顧客の債務不履行に備えて貸倒引当金を計上した。",
    choices: ["Allowance for doubtful accounts", "Bad debt expenses", "Provision for bonuses"],
    meanings: ["貸倒引当金", "貸倒損失", "賞与引当金"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産'
  },
  {
    id: 17,
    question: "Payment obligations to suppliers are shown as (　).",
    translation: "仕入先への支払義務は買掛金として示される。",
    choices: ["Accounts payable - trade", "Accrued expenses", "Advances received"],
    meanings: ["買掛金", "未払費用", "前受金"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '負債'
  },
  {
    id: 18,
    question: "The firm issued promissory notes recorded as (　).",
    translation: "会社は約束手形を発行し、支払手形として計上した。",
    choices: ["Notes payable - trade", "Accounts payable - trade", "Short-term borrowings"],
    meanings: ["支払手形", "買掛金", "短期借入金"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '負債'
  },
  {
    id: 19,
    question: "The company owns (　) for its operations.",
    translation: "会社は業務用の建物を所有している。",
    choices: ["Buildings", "Notes payable", "Accrued expenses"],
    meanings: ["建物", "支払手形", "未払費用"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産'
  },
  {
    id: 20,
    question: "Manufacturing equipment is classified as (　).",
    translation: "製造設備は機械装置として分類される。",
    choices: ["Machinery and equipment", "Tools, furniture and fixtures", "Vehicles"],
    meanings: ["機械装置", "工具器具備品", "車両運搬具"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産'
  },
  {
    id: 21,
    question: "The company owns property recorded as (　).",
    translation: "会社は土地として計上された不動産を所有している。",
    choices: ["Land", "Buildings", "Structures"],
    meanings: ["土地", "建物", "構築物"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産'
  },
  {
    id: 22,
    question: "Ongoing construction projects appear as (　) until completion.",
    translation: "進行中の建設プロジェクトは完成するまで建設仮勘定として計上される。",
    choices: ["Construction in progress", "Buildings", "Structures"],
    meanings: ["建設仮勘定", "建物", "構築物"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産'
  },
  {
    id: 23,
    question: "The total amount reducing asset value over time is shown as (　).",
    translation: "累積減価償却額は減価償却累計額として表示される。",
    choices: ["Accumulated depreciation", "Depreciation", "Impairment losses"],
    meanings: ["減価償却累計額", "減価償却費", "減損損失"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産'
  },
  {
    id: 24,
    question: "Customized applications developed internally are capitalized as (　).",
    translation: "コンピュータプログラムはソフトウエアとして資産計上される。",
    choices: ["Software", "Patent right", "Supplies"],
    meanings: ["ソフトウエア", "特許権", "貯蔵品"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産'
  },
  {
    id: 25,
    question: "Acquisition premiums from business combinations are recognized as (　).",
    translation: "企業結合による取得プレミアムはのれんとして認識される。",
    choices: ["Goodwill", "Trademark right", "Investment securities"],
    meanings: ["のれん", "商標権", "投資有価証券"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産'
  },
  {
    id: 26,
    question: "The excess of cost over fair value of net assets acquired is recorded as (　) on the balance sheet.",
    translation: "取得対価が被取得企業の純資産の公正価値を上回る部分は、貸借対照表上、のれんとして計上される。",
    choices: ["Goodwill", "Patent right", "Trademark right"],
    meanings: ["のれん", "特許権", "商標権"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産'
  },
  {
    id: 27,
    question: "Exclusive rights to inventions are shown as (　).",
    translation: "発明の独占権は特許権として示される。",
    choices: ["Patent right", "Trademark right", "Software"],
    meanings: ["特許権", "商標権", "ソフトウエア"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産'
  },
  {
    id: 28,
    question: "Expenses incurred for services received but not yet paid are recorded as (　).",
    translation: "サービスの提供を受けたが未払いの費用は未払費用として記録される。",
    choices: ["Accrued expenses", "Prepaid expenses", "Accounts payable - trade"],
    meanings: ["未払費用", "前払費用", "買掛金"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '負債'
  },
  {
    id: 29,
    question: "Amounts paid in advance are classified as (　).",
    translation: "前払いした金額は前払費用として分類される。",
    choices: ["Prepaid expenses", "Accrued expenses", "Advances received"],
    meanings: ["前払費用", "未払費用", "前受金"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産'
  },
  {
    id: 30,
    question: "Customer deposits received in advance are shown as (　).",
    translation: "顧客から事前に受け取った金額は前受金として表示される。",
    choices: ["Advances received", "Deposits received", "Accrued expenses"],
    meanings: ["前受金", "預り金", "未払費用"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '負債'
  },
  {
    id: 31,
    question: "Temporary amounts held on behalf of others are recorded as (　).",
    translation: "他者のために一時的に保管する金額は預り金として記録される。",
    choices: ["Deposits received", "Advances received", "Accrued expenses"],
    meanings: ["預り金", "前受金", "未払費用"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '負債'
  },
  {
    id: 32,
    question: "Long-term debt obligations are classified as (　).",
    translation: "長期債務は長期借入金として分類される。",
    choices: ["Long-term borrowings", "Short-term borrowings", "Bonds payable"],
    meanings: ["長期借入金", "短期借入金", "社債"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '負債'
  },
  {
    id: 33,
    question: "Debt securities issued to the public are recorded as (　).",
    translation: "発行された社債は社債として記録される。",
    choices: ["Bonds payable", "Long-term borrowings", "Notes payable - trade"],
    meanings: ["社債", "長期借入金", "支払手形"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '負債'
  },
  {
    id: 34,
    question: "Estimated future employee compensation is shown as (　).",
    translation: "従業員への予想賞与支払額は賞与引当金として示される。",
    choices: ["Provision for bonuses", "Accrued expenses", "Bonuses"],
    meanings: ["賞与引当金", "未払費用", "賞与"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '負債'
  },
  {
    id: 35,
    question: "Liabilities for employee pensions are recorded as (　).",
    translation: "従業員の年金に対する負債は退職給付に係る負債として記録される。",
    choices: ["Retirement benefit liability", "Provision for retirement benefits", "Accrued expenses"],
    meanings: ["退職給付に係る負債", "退職給付引当金", "未払費用"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '負債'
  },
  {
    id: 36,
    question: "Temporary amounts held on behalf of third parties are shown as (　).",
    translation: "第三者のために一時的に保管する金額は預り金として示される。",
    choices: ["Deposits received", "Advances received", "Accounts payable - other"],
    meanings: ["預り金", "前受金", "未払金"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '負債'
  },
  {
    id: 37,
    question: "Corporate income tax obligations are shown as (　).",
    translation: "法人所得税の債務は未払法人税等として示される。",
    choices: ["Income taxes payable", "Accrued consumption taxes", "Accrued expenses"],
    meanings: ["未払法人税等", "未払消費税等", "未払費用"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '負債'
  },
  {
    id: 38,
    question: "The company's (　) increased by 15% year on year.",
    translation: "会社の売上高は前年比15%増加した。",
    choices: ["Net sales", "Operating revenue", "Interest income"],
    meanings: ["売上高", "営業収益", "受取利息"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '収益'
  },
  {
    id: 39,
    question: "Direct costs of goods sold are shown as (　).",
    translation: "販売された商品の直接原価は売上原価として示される。",
    choices: ["Cost of sales", "Selling, general and administrative expenses", "Depreciation"],
    meanings: ["売上原価", "販売費及び一般管理費", "減価償却費"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用'
  },
  {
    id: 40,
    question: "The systematic allocation of asset cost over time is recorded as (　).",
    translation: "年間の減価償却費は減価償却費として計上される。",
    choices: ["Depreciation", "Accumulated depreciation", "Impairment losses"],
    meanings: ["減価償却費", "減価償却累計額", "減損損失"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用'
  },
  {
    id: 41,
    question: "Costs paid to lenders for borrowing money are recorded as (　).",
    translation: "借入金に係る支払利息として計上される。",
    choices: ["Interest expenses", "Commission expenses", "Insurance expenses"],
    meanings: ["支払利息", "支払手数料", "保険料"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用'
  },
  {
    id: 42,
    question: "Earnings from lending money or deposits are shown as (　).",
    translation: "貸付金や預金からの収益は受取利息として示される。",
    choices: ["Interest income", "Dividend income", "Operating revenue"],
    meanings: ["受取利息", "受取配当金", "営業収益"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '収益'
  },
  {
    id: 43,
    question: "Dividends received from investments in other companies are recorded as (　).",
    translation: "他社への投資から受け取った配当は受取配当金として記録される。",
    choices: ["Dividend income", "Interest income", "Operating revenue"],
    meanings: ["受取配当金", "受取利息", "営業収益"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '収益'
  },
  {
    id: 44,
    question: "Gains from favorable currency movements are shown as (　).",
    translation: "有利な為替変動による利益は為替差益として示される。",
    choices: ["Foreign exchange gains", "Interest income", "Gain on sale of non-current assets"],
    meanings: ["為替差益", "受取利息", "固定資産売却益"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '収益'
  },
  {
    id: 45,
    question: "Losses from unfavorable currency movements are recorded as (　).",
    translation: "不利な為替変動による損失は為替差損として記録される。",
    choices: ["Foreign exchange losses", "Interest expenses", "Loss on sale of non-current assets"],
    meanings: ["為替差損", "支払利息", "固定資産売却損"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用'
  },
  {
    id: 46,
    question: "Profits from selling fixed assets are shown as (　).",
    translation: "固定資産の売却による利益は固定資産売却益として示される。",
    choices: ["Gain on sale of non-current assets", "Interest income", "Foreign exchange gains"],
    meanings: ["固定資産売却益", "受取利息", "為替差益"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '収益'
  },
  {
    id: 47,
    question: "Losses from disposing of fixed assets are recorded as (　).",
    translation: "固定資産の処分による損失は固定資産売却損として記録される。",
    choices: ["Loss on sale of non-current assets", "Loss on retirement of non-current assets", "Impairment losses"],
    meanings: ["固定資産売却損", "固定資産除却損", "減損損失"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用'
  },
  {
    id: 48,
    question: "Asset value reductions due to impairment are shown as (　).",
    translation: "減損による資産価値の減少は減損損失として示される。",
    choices: ["Impairment losses", "Depreciation", "Loss on retirement of non-current assets"],
    meanings: ["減損損失", "減価償却費", "固定資産除却損"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用'
  },
  {
    id: 49,
    question: "Regular compensation paid to employees is recorded as (　).",
    translation: "従業員の給与および賃金は給与として計上される。",
    choices: ["Salaries", "Bonuses", "Welfare expenses"],
    meanings: ["給料", "賞与", "福利厚生費"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用'
  },
  {
    id: 50,
    question: "Employee benefits including insurance are shown as (　).",
    translation: "保険を含む従業員給付は福利厚生費として示される。",
    choices: ["Welfare expenses", "Legal welfare expenses", "Salaries"],
    meanings: ["福利厚生費", "法定福利費", "給料"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用'
  },
  {
    id: 51,
    question: "Costs for business travel are recorded as (　).",
    translation: "出張費用は旅費交通費として記録される。",
    choices: ["Travel and transportation expenses", "Communication expenses", "Meeting expenses"],
    meanings: ["旅費交通費", "通信費", "会議費"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用'
  },
  {
    id: 52,
    question: "Costs for phone, internet and mail are shown as (　).",
    translation: "電話、インターネット、郵便の費用は通信費として示される。",
    choices: ["Communication expenses", "Utilities", "Miscellaneous expenses"],
    meanings: ["通信費", "水道光熱費", "雑費"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用'
  },
  {
    id: 53,
    question: "Electricity, gas and water costs are recorded as (　).",
    translation: "電気、ガス、水道の費用は水道光熱費として記録される。",
    choices: ["Utilities", "Communication expenses", "Rent expenses"],
    meanings: ["水道光熱費", "通信費", "地代家賃"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用'
  },
  {
    id: 54,
    question: "Promotional and marketing costs are shown as (　).",
    translation: "販促及びマーケティング費用は広告宣伝費として示される。",
    choices: ["Advertising expenses", "Entertainment expenses", "Commission expenses"],
    meanings: ["広告宣伝費", "接待交際費", "支払手数料"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用'
  },
  {
    id: 55,
    question: "Business entertainment and hospitality costs are recorded as (　).",
    translation: "接待及び交際費用は接待交際費として記録される。",
    choices: ["Entertainment expenses", "Advertising expenses", "Meeting expenses"],
    meanings: ["接待交際費", "広告宣伝費", "会議費"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用'
  },
  {
    id: 56,
    question: "Property taxes and business license fees are shown as (　).",
    translation: "固定資産税及び営業許可料は租税公課として示される。",
    choices: ["Taxes and dues", "Insurance expenses", "Commission expenses"],
    meanings: ["租税公課", "保険料", "支払手数料"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用'
  },
  {
    id: 57,
    question: "Amounts paid for property and casualty coverage are recorded as (　).",
    translation: "財産及び損害保険のために支払った金額は保険料として記録される。",
    choices: ["Insurance expenses", "Taxes and dues", "Repair expenses"],
    meanings: ["保険料", "租税公課", "修繕費"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用'
  },
  {
    id: 58,
    question: "Costs for maintaining and repairing assets are shown as (　).",
    translation: "資産の維持及び修繕費用は修繕費として示される。",
    choices: ["Repair expenses", "Depreciation", "Utilities"],
    meanings: ["修繕費", "減価償却費", "水道光熱費"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用'
  },
  {
    id: 59,
    question: "Office supplies and consumables are recorded as (　).",
    translation: "事務用品及び消耗品は消耗品費として計上される。",
    choices: ["Supplies expenses", "Miscellaneous expenses", "Supplies"],
    meanings: ["消耗品費", "雑費", "貯蔵品"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用'
  },
  {
    id: 60,
    question: "Rent payments for buildings and land are shown as (　).",
    translation: "建物及び土地の賃借料は地代家賃として示される。",
    choices: ["Rent expenses", "Repair expenses", "Utilities"],
    meanings: ["地代家賃", "修繕費", "水道光熱費"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用'
  },
  {
    id: 61,
    question: "Costs for innovation and product development activities are recorded as (　).",
    translation: "研究開発支出は研究開発費として記録される。",
    choices: ["Research and development expenses", "Advertising expenses", "Commission expenses"],
    meanings: ["研究開発費", "広告宣伝費", "支払手数料"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用'
  },
  {
    id: 62,
    question: "Uncollectible receivables are written off as (　).",
    translation: "回収不能な債権は貸倒損失として償却される。",
    choices: ["Bad debt expenses", "Provision of allowance for doubtful accounts", "Impairment losses"],
    meanings: ["貸倒損失", "貸倒引当金繰入額", "減損損失"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用'
  },
  {
    id: 63,
    question: "Small uncategorized costs are recorded as (　).",
    translation: "少額の雑費は雑費として計上される。",
    choices: ["Miscellaneous expenses", "Supplies expenses", "Communication expenses"],
    meanings: ["雑費", "消耗品費", "通信費"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用'
  },
  {
    id: 64,
    question: "The company's core business income is reported as (　).",
    translation: "会社の主たる事業収入は営業収益として報告される。",
    choices: ["Operating revenue", "Net sales", "Interest income"],
    meanings: ["営業収益", "売上高", "受取利息"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '収益'
  },
  {
    id: 65,
    question: "Banks earn (　) from lending money to customers.",
    translation: "銀行は顧客への貸付から受取利息を得る。",
    choices: ["Interest income", "Dividend income", "Operating revenue"],
    meanings: ["受取利息", "受取配当金", "営業収益"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '収益'
  },
  {
    id: 66,
    question: "Shareholders receive (　) as a return on their investment.",
    translation: "株主は投資のリターンとして配当を受け取る。",
    choices: ["Dividend income", "Interest income", "Net sales"],
    meanings: ["受取配当金", "受取利息", "売上高"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '収益'
  },
  {
    id: 67,
    question: "When the yen weakens, exporters recognize (　).",
    translation: "円安時に輸出業者は為替差益を計上する。",
    choices: ["Foreign exchange gains", "Net sales", "Operating revenue"],
    meanings: ["為替差益", "売上高", "営業収益"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '収益'
  },
  {
    id: 68,
    question: "Selling equipment above book value results in (　).",
    translation: "帳簿価額を上回る価格で設備を売却すると固定資産売却益が生じる。",
    choices: ["Gain on sale of non-current assets", "Interest income", "Operating revenue"],
    meanings: ["固定資産売却益", "受取利息", "営業収益"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '収益'
  },
  {
    id: 69,
    question: "The (　) is an independent examination of financial statements.",
    translation: "財務諸表監査とは、財務諸表の独立した調査である。",
    choices: ["Financial statement audit", "Internal audit", "Tax audit"],
    meanings: ["財務諸表監査", "内部監査", "税務監査"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: '基本概念'
  },
  {
    id: 70,
    question: "The (　) is responsible for examining the financial statements.",
    translation: "監査人とは、財務諸表を調査する責任を負う者である。",
    choices: ["Auditor", "Controller", "Treasurer"],
    meanings: ["監査人", "経理部長", "財務部長"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: '基本概念'
  },
  {
    id: 71,
    question: "The (　) is the company being audited.",
    translation: "被監査会社とは、監査を受ける会社である。",
    choices: ["Audited entity", "Audit firm", "Regulatory body"],
    meanings: ["被監査会社", "監査法人", "規制機関"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: '基本概念'
  },
  {
    id: 72,
    question: "(　) is responsible for preparing the financial statements.",
    translation: "経営者とは、財務諸表を作成する責任を負う者である。",
    choices: ["Management", "Auditor", "Board of directors"],
    meanings: ["経営者", "監査人", "取締役会"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: '基本概念'
  },
  {
    id: 73,
    question: "(　) are prepared by management and examined by auditors.",
    translation: "財務諸表とは、経営者によって作成され監査人によって調査されるものである。",
    choices: ["Financial statements", "Audit reports", "Tax returns"],
    meanings: ["財務諸表", "監査報告書", "税務申告書"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: '基本概念'
  },
  {
    id: 74,
    question: "(　) provide guidelines for conducting audits.",
    translation: "監査基準とは、監査の実施に関する指針を提供するものである。",
    choices: ["Auditing standards", "Accounting standards", "Tax regulations"],
    meanings: ["監査基準", "会計基準", "税務規則"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: '基本概念'
  },
  {
    id: 75,
    question: "(　) are the auditing standards accepted in a jurisdiction.",
    translation: "一般に公正妥当と認められた監査の基準とは、その管轄区域で認められた監査基準である。",
    choices: ["Generally Accepted Auditing Standards (GAAS)", "International Standards on Auditing (ISA)", "Financial Accounting Standards"],
    meanings: ["一般に公正妥当と認められた監査の基準", "国際監査基準", "財務会計基準"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: '基本概念'
  },
  {
    id: 76,
    question: "(　) are globally recognized auditing standards.",
    translation: "国際監査基準とは、世界的に認められた監査基準である。",
    choices: ["International Standards on Auditing (ISA)", "Generally Accepted Auditing Standards (GAAS)", "National auditing standards"],
    meanings: ["国際監査基準", "一般に公正妥当と認められた監査の基準", "国内監査基準"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: '基本概念'
  },
  {
    id: 77,
    question: "(　) involves developing a strategy for the audit engagement.",
    translation: "監査計画とは、監査業務の戦略を策定することを含むものである。",
    choices: ["Audit planning", "Audit execution", "Audit reporting"],
    meanings: ["監査計画", "監査実施", "監査報告"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: 'リスク・手続'
  },
  {
    id: 78,
    question: "(　) refers to omissions or misstatements of items that could, individually or collectively, influence the economic decisions that users make on the basis of the financial statements.",
    translation: "重要性とは、財務諸表を基礎として利用者が行う経済的意思決定に、個別または集計して影響を与える可能性がある項目の脱漏又は虚偽表示を指すものである。",
    choices: ["Materiality", "Audit risk", "Control environment"],
    meanings: ["重要性", "監査リスク", "統制環境"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: 'リスク・手続'
  },
  {
    id: 79,
    question: "(　) is the risk that the auditor expresses an inappropriate audit opinion when the financial statements are materially misstated.",
    translation: "監査リスクとは、財務諸表に重要な虚偽表示が存在しているにもかかわらず、監査人が誤った監査意見を表明するリスクである。",
    choices: ["Audit risk", "Business risk", "Financial risk"],
    meanings: ["監査リスク", "事業リスク", "財務リスク"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: 'リスク・手続'
  },
  {
    id: 80,
    question: "(　) is the susceptibility of an assertion about a class of transactions, account balance or disclosure to a misstatement that could be material, before consideration of any related controls.",
    translation: "固有リスクとは、関連する内部統制が存在しないと仮定した場合に、取引種類、勘定残高又は開示等に関する経営者の主張に重要な虚偽表示が含まれる可能性である。",
    choices: ["Inherent risk", "Control risk", "Detection risk"],
    meanings: ["固有リスク", "統制リスク", "発見リスク"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: 'リスク・手続'
  },
  {
    id: 81,
    question: "(　) is the risk that a misstatement that could occur in an assertion and that could be material will not be prevented, or detected and corrected, on a timely basis by the entity's internal control.",
    translation: "統制リスクとは、取引種類、勘定残高又は開示等に関する経営者の主張に含まれる重要な虚偽表示が、企業の内部統制によって防止、または発見され、適時に是正されないリスクである。",
    choices: ["Control risk", "Inherent risk", "Detection risk"],
    meanings: ["統制リスク", "固有リスク", "発見リスク"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: 'リスク・手続'
  },
  {
    id: 82,
    question: "(　) is the risk that the procedures performed by the auditor to reduce audit risk to an acceptably low level will not detect a misstatement that exists and that could be material.",
    translation: "発見リスクとは、監査リスクを十分に低い水準に抑えるために監査人が実施する監査手続が、存在する重要な虚偽表示を発見できないリスクである。",
    choices: ["Detection risk", "Inherent risk", "Control risk"],
    meanings: ["発見リスク", "固有リスク", "統制リスク"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: 'リスク・手続'
  },
  {
    id: 83,
    question: "(　) is a process designed and effected by those charged with governance, management and other personnel to provide reasonable assurance regarding the achievement of objectives relating to operations, reporting, and compliance.",
    translation: "内部統制とは、業務の有効性・効率性、財務報告の信頼性、法令等の遵守及び資産の保全という目的達成について合理的な保証を得るために、組織内の全員によって遂行されるプロセスである。",
    choices: ["Internal control", "External audit", "Compliance program"],
    meanings: ["内部統制", "外部監査", "コンプライアンスプログラム"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: 'リスク・手続'
  },
  {
    id: 84,
    question: "An (　) examines the effectiveness of internal controls.",
    translation: "内部統制監査とは、内部統制の有効性を調査するものである。",
    choices: ["Audit of internal control", "Financial statement audit", "Compliance audit"],
    meanings: ["内部統制監査", "財務諸表監査", "コンプライアンス監査"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: 'リスク・手続'
  },
  {
    id: 85,
    question: "(　) involves identifying and analyzing risks of material misstatement.",
    translation: "リスク評価とは、重要な虚偽表示のリスクを識別し分析することを含むものである。",
    choices: ["Risk assessment", "Risk mitigation", "Risk monitoring"],
    meanings: ["リスク評価", "リスク軽減", "リスク監視"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: 'リスク・手続'
  },
  {
    id: 86,
    question: "(　) require special audit consideration due to their nature.",
    translation: "特別な検討を必要とするリスクとは、その性質により特別な監査上の配慮を必要とするものである。",
    choices: ["Significant risks", "Routine risks", "Minimal risks"],
    meanings: ["特別な検討を必要とするリスク", "定型的リスク", "最小限のリスク"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: 'リスク・手続'
  },
  {
    id: 87,
    question: "(　) is an intentional act by one or more individuals among management, those charged with governance, employees, or third parties, involving the use of deception to obtain an unjust or illegal advantage.",
    translation: "不正とは、経営者、統治責任者、従業員又は第三者による、欺罔を用いて不当又は違法な利益を得るための意図的な行為である。",
    choices: ["Fraud", "Error", "Negligence"],
    meanings: ["不正", "誤謬", "過失"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: 'リスク・手続'
  },
  {
    id: 88,
    question: "An (　) is an unintentional misstatement in financial statements, including the omission of an amount or disclosure.",
    translation: "誤謬とは、金額又は開示の脱漏を含む、財務諸表における意図的でない虚偽表示である。",
    choices: ["Error", "Fraud", "Violation"],
    meanings: ["誤謬", "不正", "違反"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: 'リスク・手続'
  },
  {
    id: 89,
    question: "(　) is an attitude that includes a questioning mind, being alert to conditions that may indicate possible misstatement due to fraud or error, and a critical assessment of audit evidence.",
    translation: "職業的懐疑心とは、不正又は誤謬による虚偽表示の可能性を示す状況に注意を払い、監査証拠を批判的に評価することを含む、疑いを持って考える姿勢である。",
    choices: ["Professional skepticism", "Professional judgment", "Professional competence"],
    meanings: ["職業的懐疑心", "職業的判断", "職業的能力"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: '基本概念'
  },
  {
    id: 90,
    question: "(　) is the application of relevant training, knowledge and experience to make informed decisions about the courses of action that are appropriate in the circumstances of the audit engagement.",
    translation: "職業的判断とは、監査業務の状況において適切な行動を決定するために、関連する訓練、知識及び経験を適用することである。",
    choices: ["Professional judgment", "Professional skepticism", "Professional ethics"],
    meanings: ["職業的判断", "職業的懐疑心", "職業倫理"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: '基本概念'
  },
  {
    id: 91,
    question: "(　) comprises both information that supports and corroborates management's assertions, and any information that contradicts such assertions.",
    translation: "監査証拠とは、経営者の主張を裏付ける情報、及びそれらの主張と矛盾する情報の両方を含むものである。",
    choices: ["Audit evidence", "Financial data", "Management assertions"],
    meanings: ["監査証拠", "財務データ", "経営者の主張"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: 'リスク・手続'
  },
  {
    id: 92,
    question: "The auditor shall design and perform audit procedures to obtain (　), which comprises both the quantity and quality of evidence needed.",
    translation: "監査人は、監査証拠の量と質の両方を含む十分かつ適切な監査証拠を入手するために、監査手続を立案し実施しなければならない。",
    choices: ["Sufficient and appropriate audit evidence", "All available evidence", "Management's evidence"],
    meanings: ["十分かつ適切な監査証拠", "全ての利用可能な証拠", "経営者の証拠"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: 'リスク・手続'
  },
  {
    id: 93,
    question: "(　) test the accuracy of account balances and transactions.",
    translation: "実証手続とは、勘定残高と取引の正確性をテストするものである。",
    choices: ["Substantive procedures", "Tests of controls", "Compliance procedures"],
    meanings: ["実証手続", "統制テスト", "コンプライアンス手続"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: 'リスク・手続'
  },
  {
    id: 94,
    question: "(　) evaluate the operating effectiveness of internal controls.",
    translation: "統制テストとは、内部統制の運用の有効性を評価するものである。",
    choices: ["Tests of controls", "Substantive procedures", "Analytical procedures"],
    meanings: ["統制テスト", "実証手続", "分析的手続"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: 'リスク・手続'
  },
  {
    id: 95,
    question: "(　) assess whether controls are operating as designed.",
    translation: "運用評価手続とは、統制が設計通りに運用されているかを評価するものである。",
    choices: ["Tests of operating effectiveness", "Design testing", "Implementation testing"],
    meanings: ["運用評価手続", "設計テスト", "実装テスト"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: 'リスク・手続'
  },
  {
    id: 96,
    question: "(　) involve analyzing relationships among financial and non-financial data.",
    translation: "分析的手続とは、財務データと非財務データの関係を分析することを含むものである。",
    choices: ["Analytical procedures", "Substantive testing", "Compliance testing"],
    meanings: ["分析的手続", "実証テスト", "コンプライアンステスト"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: 'リスク・手続'
  },
  {
    id: 97,
    question: "(　) are the records of audit procedures performed and conclusions reached.",
    translation: "監査調書とは、実施した監査手続と到達した結論の記録である。",
    choices: ["Audit documentation", "Financial statements", "Management letters"],
    meanings: ["監査調書", "財務諸表", "マネジメントレター"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: 'リスク・手続'
  },
  {
    id: 98,
    question: "(　) is the selection of items to test from a population.",
    translation: "サンプリングとは、母集団からテストする項目を選択することである。",
    choices: ["Audit sampling", "Census testing", "Judgmental selection"],
    meanings: ["サンプリング", "全数テスト", "判断的選択"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: 'リスク・手続'
  },
  {
    id: 99,
    question: "(　) defines the extent and boundaries of the audit engagement.",
    translation: "監査範囲とは、監査業務の範囲と境界を定義するものである。",
    choices: ["Audit scope", "Audit strategy", "Audit plan"],
    meanings: ["監査範囲", "監査戦略", "監査計画"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: 'リスク・手続'
  },
  {
    id: 100,
    question: "The (　) is the auditor's conclusion on the financial statements.",
    translation: "監査意見とは、財務諸表に関する監査人の結論である。",
    choices: ["Audit opinion", "Management assertion", "Financial analysis"],
    meanings: ["監査意見", "経営者の主張", "財務分析"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: '監査報告'
  },
  {
    id: 101,
    question: "An (　) states that financial statements are fairly presented.",
    translation: "無限定適正意見とは、財務諸表が適正に表示されていると述べるものである。",
    choices: ["Unmodified opinion", "Qualified opinion", "Adverse opinion"],
    meanings: ["無限定適正意見", "限定付適正意見", "不適正意見"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: '監査報告'
  },
  {
    id: 102,
    question: "A (　) is issued when there is a material but not pervasive misstatement.",
    translation: "限定付適正意見とは、重要だが広範でない虚偽表示がある場合に表明されるものである。",
    choices: ["Qualified opinion", "Unmodified opinion", "Adverse opinion"],
    meanings: ["限定付適正意見", "無限定適正意見", "不適正意見"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: '監査報告'
  },
  {
    id: 103,
    question: "An (　) states that financial statements are materially misstated.",
    translation: "不適正意見とは、財務諸表が重要に虚偽表示されていると述べるものである。",
    choices: ["Adverse opinion", "Qualified opinion", "Unmodified opinion"],
    meanings: ["不適正意見", "限定付適正意見", "無限定適正意見"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: '監査報告'
  },
  {
    id: 104,
    question: "A (　) is issued when the auditor cannot obtain sufficient evidence.",
    translation: "意見不表明とは、監査人が十分な証拠を入手できない場合に表明されるものである。",
    choices: ["Disclaimer of opinion", "Qualified opinion", "Adverse opinion"],
    meanings: ["意見不表明", "限定付適正意見", "不適正意見"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: '監査報告'
  },
  {
    id: 105,
    question: "The (　) communicates the auditor's findings to users.",
    translation: "監査報告書とは、監査人の発見事項を利用者に伝達するものである。",
    choices: ["Auditor's report", "Management letter", "Financial statements"],
    meanings: ["監査報告書", "マネジメントレター", "財務諸表"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: '監査報告'
  },
  {
    id: 106,
    question: "An (　) highlights matters that are appropriately presented in financial statements.",
    translation: "強調事項区分とは、財務諸表に適切に表示されている事項を強調するものである。",
    choices: ["Emphasis of matter paragraph", "Qualified opinion", "Disclaimer"],
    meanings: ["強調事項区分", "限定付意見", "意見不表明"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: '監査報告'
  },
  {
    id: 107,
    question: "The (　) assumes that the entity will continue operations.",
    translation: "継続企業の前提とは、企業が事業を継続することを前提とするものである。",
    choices: ["Going concern assumption", "Liquidation basis", "Historical cost"],
    meanings: ["継続企業の前提", "清算基準", "取得原価"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: 'リスク・手続'
  },
  {
    id: 108,
    question: "(　) involve uncertainty and require management judgment.",
    translation: "会計上の見積りとは、不確実性を含み経営者の判断を必要とするものである。",
    choices: ["Accounting estimates", "Historical costs", "Actual transactions"],
    meanings: ["会計上の見積り", "取得原価", "実際の取引"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: 'リスク・手続'
  },
  {
    id: 109,
    question: "A (　) is an error or fraud that affects financial statement fairness.",
    translation: "重要な虚偽表示とは、財務諸表の適正性に影響を与える誤謬または不正である。",
    choices: ["Material misstatement", "Minor error", "Disclosure note"],
    meanings: ["重要な虚偽表示", "軽微な誤り", "開示注記"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: 'リスク・手続'
  },
  {
    id: 110,
    question: "A (　) is an inaccuracy in the financial statements.",
    translation: "虚偽表示とは、財務諸表における不正確さである。",
    choices: ["Misstatement", "Disclosure", "Adjustment"],
    meanings: ["虚偽表示", "開示", "修正"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: 'リスク・手続'
  },
  {
    id: 111,
    question: "(　) are errors that management has not corrected.",
    translation: "未修正虚偽表示とは、経営者が修正していない誤謬である。",
    choices: ["Uncorrected misstatement", "Adjusted misstatement", "Material weakness"],
    meanings: ["未修正虚偽表示", "修正済虚偽表示", "重要な不備"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: 'リスク・手続'
  },
  {
    id: 112,
    question: "(　) includes prior period figures for comparison purposes.",
    translation: "比較情報とは、比較目的のため前期の数値を含むものである。",
    choices: ["Comparative information", "Current period data", "Budget information"],
    meanings: ["比較情報", "当期データ", "予算情報"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: 'リスク・手続'
  },
  {
    id: 113,
    question: "(　) are the balances at the beginning of the period.",
    translation: "期首残高とは、期間の開始時点の残高である。",
    choices: ["Opening balances", "Closing balances", "Average balances"],
    meanings: ["期首残高", "期末残高", "平均残高"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: 'リスク・手続'
  },
  {
    id: 114,
    question: "(　) are individuals or entities with special relationships to the company.",
    translation: "関連当事者とは、会社と特別な関係を持つ個人または組織である。",
    choices: ["Related parties", "External parties", "Independent parties"],
    meanings: ["関連当事者", "外部当事者", "独立当事者"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: 'リスク・手続'
  },
  {
    id: 115,
    question: "(　) are events occurring after the reporting period.",
    translation: "後発事象とは、報告期間後に発生する事象である。",
    choices: ["Subsequent events", "Prior period events", "Current events"],
    meanings: ["後発事象", "前期事象", "当期事象"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: 'リスク・手続'
  },
  {
    id: 116,
    question: "A (　) is a written statement from management confirming certain matters.",
    translation: "経営者確認書とは、特定の事項を確認する経営者からの書面である。",
    choices: ["Management representation letter", "Audit report", "Financial statement"],
    meanings: ["経営者確認書", "監査報告書", "財務諸表"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: 'リスク・手続'
  },
  {
    id: 117,
    question: "A (　) monitors the board of directors in Japanese companies.",
    translation: "監査役とは、日本企業において取締役会を監視する者である。",
    choices: ["Statutory auditor", "External auditor", "Internal auditor"],
    meanings: ["監査役", "外部監査人", "内部監査人"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: '基本概念'
  },
  {
    id: 118,
    question: "The (　) is a governance body in Japanese companies.",
    translation: "監査役会とは、日本企業におけるガバナンス機関である。",
    choices: ["Board of statutory auditors", "Audit committee", "Board of directors"],
    meanings: ["監査役会", "監査委員会", "取締役会"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: '基本概念'
  },
  {
    id: 119,
    question: "An (　) oversees financial reporting and external audits.",
    translation: "監査委員会とは、財務報告と外部監査を監督するものである。",
    choices: ["Audit committee", "Board of statutory auditors", "Management team"],
    meanings: ["監査委員会", "監査役会", "経営チーム"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: '基本概念'
  },
  {
    id: 120,
    question: "(　) is an independent evaluation of internal controls and operations.",
    translation: "内部監査とは、内部統制と業務の独立した評価である。",
    choices: ["Internal audit", "External audit", "Compliance review"],
    meanings: ["内部監査", "外部監査", "コンプライアンスレビュー"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: '基本概念'
  },
  {
    id: 121,
    question: "An (　) performs internal audit activities within the organization.",
    translation: "内部監査人とは、組織内で内部監査活動を実施する者である。",
    choices: ["Internal auditor", "External auditor", "Compliance officer"],
    meanings: ["内部監査人", "外部監査人", "コンプライアンス担当者"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: '基本概念'
  },
  {
    id: 122,
    question: "(　) are controls over information technology systems.",
    translation: "IT統制とは、情報技術システムに対する統制である。",
    choices: ["IT controls", "Manual controls", "Physical controls"],
    meanings: ["IT統制", "手作業統制", "物理的統制"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: 'リスク・手続'
  },
  {
    id: 123,
    question: "(　) support the overall IT environment and operations.",
    translation: "全般統制とは、IT環境全体と運用を支援するものである。",
    choices: ["General IT controls", "Application controls", "User controls"],
    meanings: ["全般統制", "業務処理統制", "利用者統制"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: 'リスク・手続'
  },
  {
    id: 124,
    question: "(　) are controls embedded in business applications.",
    translation: "業務処理統制とは、業務アプリケーションに組み込まれた統制である。",
    choices: ["Application controls", "General IT controls", "Physical controls"],
    meanings: ["業務処理統制", "全般統制", "物理的統制"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: 'リスク・手続'
  },
  {
    id: 125,
    question: "A (　) is a weakness in the design or operation of controls.",
    translation: "内部統制の不備とは、統制の設計または運用における弱点である。",
    choices: ["Deficiency in internal control", "Control strength", "Control enhancement"],
    meanings: ["内部統制の不備", "統制の強み", "統制の強化"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: 'リスク・手続'
  },
  {
    id: 126,
    question: "(　) involves intentional misstatement of financial statements.",
    translation: "不正な財務報告とは、財務諸表の意図的な虚偽表示を含むものである。",
    choices: ["Fraudulent financial reporting", "Management error", "Accounting mistake"],
    meanings: ["不正な財務報告", "経営者の誤謬", "会計上の誤り"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: 'リスク・手続'
  },
  {
    id: 127,
    question: "(　) is the theft or misuse of an entity's assets.",
    translation: "横領とは、組織の資産の盗難または不正使用である。",
    choices: ["Misappropriation of assets", "Asset valuation", "Asset disposal"],
    meanings: ["横領", "資産評価", "資産処分"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: 'リスク・手続'
  },
  {
    id: 128,
    question: "An (　) is the agreement between the auditor and client.",
    translation: "監査契約とは、監査人と依頼人の間の合意である。",
    choices: ["Audit engagement", "Service agreement", "Consulting contract"],
    meanings: ["監査契約", "サービス契約", "コンサルティング契約"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: '基本概念'
  },
  {
    id: 129,
    question: "(　) means being free from conflicts of interest.",
    translation: "独立性とは、利害の衝突がないことを意味する。",
    choices: ["Independence", "Objectivity", "Competence"],
    meanings: ["独立性", "客観性", "能力"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: '基本概念'
  },
  {
    id: 132,
    question: "A (　) occurs when personal interests interfere with professional duties.",
    translation: "利害関係とは、個人的利益が職業的義務と干渉する時に発生するものである。",
    choices: ["Conflict of interest", "Professional relationship", "Business partnership"],
    meanings: ["利害関係", "職業的関係", "事業提携"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: '基本概念'
  },
  {
    id: 133,
    question: "(　) requires auditors to protect client information.",
    translation: "守秘義務とは、監査人に依頼人の情報を保護することを要求するものである。",
    choices: ["Confidentiality", "Transparency", "Disclosure"],
    meanings: ["守秘義務", "透明性", "開示"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: '基本概念'
  },
  {
    id: 134,
    question: "(　) ensures consistent standards in audit engagements.",
    translation: "品質管理とは、監査業務における一貫した基準を保証するものである。",
    choices: ["Quality control", "Quality assurance", "Quality improvement"],
    meanings: ["品質管理", "品質保証", "品質改善"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: '基本概念'
  },
  {
    id: 135,
    question: "An (　) is a professional services firm that performs audits.",
    translation: "監査法人とは、監査を実施する専門サービス会社である。",
    choices: ["Audit firm", "Consulting firm", "Law firm"],
    meanings: ["監査法人", "コンサルティング会社", "法律事務所"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: '基本概念'
  },
  {
    id: 136,
    question: "The (　) is the partner responsible for the audit engagement.",
    translation: "業務執行社員とは、監査業務に責任を負うパートナーである。",
    choices: ["Engagement partner", "Audit manager", "Staff auditor"],
    meanings: ["業務執行社員", "監査マネージャー", "スタッフ監査人"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: '基本概念'
  },
  {
    id: 137,
    question: "The (　) includes all personnel performing the audit.",
    translation: "チームメンバーとは、監査を実施する全ての人員を含むものである。",
    choices: ["Engagement team", "Management team", "Audit committee"],
    meanings: ["チームメンバー", "経営チーム", "監査委員会"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: '基本概念'
  },
  {
    id: 138,
    question: "The (　) is to enhance the degree of confidence of intended users in the financial statements by expressing an opinion on whether the financial statements are prepared, in all material respects, in accordance with an applicable financial reporting framework.",
    translation: "監査の目的は、財務諸表が適正に表示されているかについて意見を表明し、財務諸表の信頼性を保証することにより、利用者の意思決定に寄与することである。",
    choices: ["Objective of the audit", "Audit procedure", "Audit scope"],
    meanings: ["監査の目的", "監査手続", "監査範囲"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: '基本概念'
  },
  {
    id: 139,
    question: "(　) is a high level of assurance, but not an absolute guarantee, that is achieved when the auditor has obtained sufficient appropriate audit evidence.",
    translation: "合理的な保証は、監査人が十分かつ適切な監査証拠を入手した場合に達成される、高い水準の保証であるが、絶対的な保証ではない。",
    choices: ["Reasonable assurance", "Absolute assurance", "Limited assurance"],
    meanings: ["合理的保証", "絶対的保証", "限定的保証"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: '基本概念'
  },
  {
    id: 140,
    question: "(　) is a guarantee that cannot be achieved in an audit.",
    translation: "絶対的保証は監査では達成できない保証である。",
    choices: ["Absolute assurance", "Reasonable assurance", "Limited assurance"],
    meanings: ["絶対的保証", "合理的保証", "限定的保証"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: '基本概念'
  },
  {
    id: 141,
    question: "(　) are unavoidable restrictions on the audit's ability to detect all misstatements.",
    translation: "固有の限界とは、全ての虚偽表示を発見する監査の能力における避けられない制約である。",
    choices: ["Inherent limitations", "Scope limitations", "Resource limitations"],
    meanings: ["固有の限界", "範囲の制約", "資源の制約"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: '基本概念'
  },
  {
    id: 142,
    question: "(　) are signs that fraud may be present.",
    translation: "不正の兆候とは、不正が存在する可能性を示す徴候である。",
    choices: ["Indicators of fraud", "Fraud evidence", "Fraud detection"],
    meanings: ["不正の兆候", "不正の証拠", "不正の発見"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: 'リスク・手続'
  },
  {
    id: 143,
    question: "(　) occurs when management circumvents established controls.",
    translation: "経営者による内部統制の無効化とは、経営者が確立された統制を回避する時に発生するものである。",
    choices: ["Management override of controls", "Control failure", "System error"],
    meanings: ["経営者による内部統制の無効化", "統制の失敗", "システムエラー"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: 'リスク・手続'
  },
  {
    id: 144,
    question: "(　) involves engaging a specialist to assist with the audit.",
    translation: "専門家の利用とは、監査を支援するために専門家を起用することを含むものである。",
    choices: ["Use of an auditor's expert", "Internal consultation", "Peer review"],
    meanings: ["専門家の利用", "内部相談", "ピアレビュー"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: 'リスク・手続'
  },
  {
    id: 145,
    question: "(　) means relying on internal audit work for external audit purposes.",
    translation: "内部監査人の業務の利用とは、外部監査目的で内部監査の業務に依拠することを意味する。",
    choices: ["Using the work of internal auditors", "Internal audit outsourcing", "Audit cooperation"],
    meanings: ["内部監査人の業務の利用", "内部監査の外部委託", "監査協力"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: 'リスク・手続'
  },
  {
    id: 146,
    question: "A (　) audits a component of a group.",
    translation: "構成単位の監査人はグループの構成単位を監査する。",
    choices: ["Component auditor", "Group auditor", "Lead auditor"],
    meanings: ["構成単位の監査人", "グループ監査人", "主任監査人"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: '監査報告'
  },
  {
    id: 147,
    question: "A (　) involves auditing consolidated financial statements.",
    translation: "グループ監査とは、連結財務諸表の監査を含むものである。",
    choices: ["Group audit", "Single entity audit", "Branch audit"],
    meanings: ["グループ監査", "単一組織監査", "支店監査"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: '監査報告'
  },
  {
    id: 148,
    question: "A (　) is a component that is material to the group.",
    translation: "重要な構成単位とは、グループにとって重要な構成単位である。",
    choices: ["Significant component", "Minor component", "Immaterial component"],
    meanings: ["重要な構成単位", "軽微な構成単位", "重要でない構成単位"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: '監査報告'
  },
  {
    id: 149,
    question: "An (　) examines consolidated financial statements.",
    translation: "連結財務諸表監査とは、連結財務諸表を調査するものである。",
    choices: ["Audit of consolidated financial statements", "Single entity audit", "Divisional audit"],
    meanings: ["連結財務諸表監査", "単一組織監査", "事業部監査"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: '監査報告'
  },
  {
    id: 150,
    question: "(　) is the physical examination of assets or documents.",
    translation: "実査は、資産の現物を実際に確認する監査手続である。",
    choices: ["Physical inspection", "Document review", "Inquiry"],
    meanings: ["実査", "文書レビュー", "質問"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: 'リスク・手続'
  },
  {
    id: 151,
    question: "(　) consists of looking at a process or procedure being performed by others.",
    translation: "立会は、他の者が実施するプロセス又は手続を観察する監査手続である。",
    choices: ["Observation", "Inspection", "Inquiry"],
    meanings: ["立会", "閲覧", "質問"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: 'リスク・手続'
  },
  {
    id: 152,
    question: "(　) represents audit evidence obtained as a direct written response to the auditor from a third party.",
    translation: "確認は、監査人が第三者から書面による回答を直接入手する監査証拠である。",
    choices: ["Confirmation", "Inquiry", "Inspection"],
    meanings: ["確認", "質問", "閲覧"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: 'リスク・手続'
  },
  {
    id: 153,
    question: "(　) involves examining records or documents, whether internal or external, in paper form, electronic form, or other media.",
    translation: "閲覧は、内部又は外部の記録や文書を、紙媒体、電子媒体その他の媒体の形式を問わず調査する監査手続である。",
    choices: ["Inspection", "Observation", "Reperformance"],
    meanings: ["閲覧", "立会", "再実施"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: 'リスク・手続'
  },
  {
    id: 154,
    question: "(　) consists of checking the mathematical accuracy of documents or records.",
    translation: "再計算は、文書又は記録の計算の正確性を検証する監査手続である。",
    choices: ["Recalculation", "Reperformance", "Analytical procedure"],
    meanings: ["再計算", "再実施", "分析的手続"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: 'リスク・手続'
  },
  {
    id: 155,
    question: "(　) is the auditor's independent execution of procedures or controls that were originally performed as part of the entity's internal control.",
    translation: "再実施は、監査人が、企業の内部統制の一部として実施されている手続又は統制活動を独自に実行する監査手続である。",
    choices: ["Reperformance", "Recalculation", "Observation"],
    meanings: ["再実施", "再計算", "立会"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: 'リスク・手続'
  },
  {
    id: 156,
    question: "(　) consists of seeking information of knowledgeable persons, both financial and non-financial, within the entity or outside the entity.",
    translation: "質問は、企業内外の財務的又は非財務的な事項に関する知識を有する者に対して情報を求める監査手続である。",
    choices: ["Inquiry", "Confirmation", "Observation"],
    meanings: ["質問", "確認", "立会"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: 'リスク・手続'
  },
  {
    id: 157,
    question: "(　) is the process of preparing financial information.",
    translation: "財務報告とは、財務情報を作成するプロセスである。",
    choices: ["Financial reporting", "Financial analysis", "Financial planning"],
    meanings: ["財務報告", "財務分析", "財務計画"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: '基本概念'
  },
  {
    id: 158,
    question: "The (　) is the auditor's final assessment based on audit evidence.",
    translation: "監査の結論とは、監査証拠に基づく監査人の最終的な評価である。",
    choices: ["Audit conclusion", "Audit plan", "Audit scope"],
    meanings: ["監査の結論", "監査計画", "監査範囲"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: '監査報告'
  },
  {
    id: 159,
    question: "(　) are those matters that, in the auditor's professional judgment, were of most significance in the audit of the financial statements of the current period.",
    translation: "監査上の主要な検討事項は、監査人が職業的専門家として、当年度の財務諸表の監査において最も重要であると判断した事項である。",
    choices: ["Key audit matters (KAMs)", "Routine audit matters", "Administrative matters"],
    meanings: ["監査上の主要な検討事項", "定型的監査事項", "管理事項"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: '監査報告'
  }
];
